plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "me.modmuss50.mod-publish-plugin"
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation "com.google.code.findbugs:jsr305:3.0.1"
    implementation project(":common")

    modImplementation include("com.coolerpromc.coolerconfig:coolerconfig-fabric-${minecraft_version}:${cooler_config_version}")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        client2 {
            client()
            setConfigName('Fabric Client 2')
            ideConfigGenerated(true)
            runDir('runs/client2')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publishMods {
    file.set(remapJar.archiveFile)
    type = BETA
    modLoaders.add("fabric")
    changelog = rootProject.file("changelog.md").text
    displayName = mod_id + "-" + project.version + "+" + minecraft_version + "-fabric"

    curseforge {
        projectId = "1569997"
        accessToken = findProperty("CF_TOKEN")
        minecraftVersions.add(minecraft_version)

        client = true
        server = true
    }

    modrinth {
        projectId = 'ThJBmy1K'
        accessToken = findProperty("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
    }
}