plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id "me.modmuss50.mod-publish-plugin"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge   {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "Forge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            gameDirectory = this.mkdir(this.file("runs/client"))
        }
        client2{
            client()
            programArguments.add('--username')
            programArguments.add('Dev2')
            gameDirectory = this.mkdir(this.file("runs/client2"))
        }
        data {
            data()
            gameDirectory = this.mkdir(this.file("runs/data"))
            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            gameDirectory = this.mkdir(this.file("runs/server"))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")

    jarJar implementation("com.coolerpromc.coolerconfig:coolerconfig-forge-${minecraft_version}:${cooler_config_version}")
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

tasks.publishMods.dependsOn(tasks.reobfJar)

publishMods {
    file.set(tasks.named('reobfJar').flatMap { it.archiveFile })
    type = BETA
    modLoaders.add("forge")
    changelog = rootProject.file("changelog.md").text
    displayName = mod_id + "-" + project.version + "+" + minecraft_version + "-forge"

    curseforge {
        projectId = "1569997"
        accessToken = findProperty("CF_TOKEN")
        minecraftVersions.add(minecraft_version)

        client = true
        server = true
    }

    modrinth {
        projectId = 'ThJBmy1K'
        accessToken = findProperty("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
    }
}